name: CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branche de build'
        required: true
        default: 'feat/add-flare-solverr-bypass-cf'
  pull_request:
    branches:
      - feat/add-flare-solverr-bypass-cf
  push:
    branches:
      - feat/add-flare-solverr-bypass-cf

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build app
        run: ./gradlew spotlessCheck assembleDevRelease

      - name: List APK output
        run: ls -R app/build/outputs/apk/

      - name: Upload APKs
        uses: actions/upload-artifact@v7
        with:
          name: TachiyomiSY-${{ github.sha }}-apks
          path: app/build/outputs/apk/release/*.apk
